spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        clientId: your-client-id
        clientSecret: your-client-secret
